version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 25
    package-ecosystem: maven
    schedule:
      interval: daily
      time: "04:00"
  - directory: "/client"
    open-pull-requests-limit: 25
    package-ecosystem: npm
    schedule:
      interval: daily
      time: "04:00"
