cudami:
  typeDeclarations:
    involvementRoles:
    - ILLUSTRATOR
    - AUTHOR
    - COMPOSER
    - CREATOR_UNSPECIFIED
    - CONTRIB_PERFORMANCE
    - CONTRIB_PRODUCTION
    - CONTRIB_TEXT
    - CONTRIB_VISUALARTS
    - EDITOR
    - RELATION_TO_OBJECT
    - TRANSLATOR
    - VISUALARTIST
    - OTHER

    manufacturingTypes:
    - PRINT
    - HANDMADE

    mediaTypes: #TODO
    - BOOK

    tagTypes: #TODO
    - TAG

    expressionTypes: #TODO
    - mainType: TEXT
      subType: HANDWRITING

    titleTypes:
    - mainType: ABBR
      subType: MAIN
    - mainType: ALT
      subType: MAIN
    - mainType: ALT
      subType: SUB
    - mainType: ALT
      subType: PART
    - mainType: FORMER
      subType: MAIN
    - mainType: FORMER
      subType: PART
    - mainType: FORMER
      subType: SUB
    - mainType: HOST
      subType:
    - mainType: MAIN
      subType: MAIN
    - mainType: MAIN
      subType: PART
    - mainType: MAIN
      subType: SUB
    - mainType: PAR
      subType: MAIN
    - mainType: PAR
      subType: PART
    - mainType: PAR
      subType: SUB
    - mainType: TRANS
      subType: MAIN
    - mainType: TRANS
      subType: PART
    - mainType: TRANS
      subType: SUB
    - mainType: UNI
      subType: MAIN
    - mainType: UNI
      subType: PART
    - mainType: UNI
      subType: SUB
