FROM eclipse-temurin:11-jre-jammy

RUN apt-get update && apt-get install -y libopenjp2-7 libturbojpeg

ARG HYMIR_VERSION

ADD https://oss.sonatype.org/content/repositories/releases/de/digitalcollections/iiif-server-hymir/$HYMIR_VERSION/iiif-server-hymir-$HYMIR_VERSION-exec.jar hymir.jar

ENTRYPOINT [ "java", "-jar", "/hymir.jar", "--management.server.port=9001", "--server.port=9000", "--spring.config.additional-location=file:/application-iiif.yml" ]
