cudami:
  defaultLocale-gui: en
  prioritisedSortedLanguages: ''
  server:
    address: http://localhost:9000
    url: http://localhost:9000

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      artifactId: '@project.artifactId@'
      buildDetails: '@versionName@'
      groupId: '@project.groupId@'
      name: '@project.name@'
      version: '@project.version@'

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  server:
    port: 19898

server:
  port: 9898
  server-header: "@project.name@ v@project.version@"
  servlet:
    session:
      cookie:
        http-only: true
        name: CUDAMI_SESSION_ID
        secure: false
      timeout: 10h
      tracking-modes: cookie

# upload config: see org.springframework.boot.autoconfigure.web.MultipartProperties
spring:
  main:
    banner-mode: 'off'
  messages:
    basename: messages, messages-commons
    fallback-to-system-locale: false
  profiles:
    active: local
  security:
    rememberme:
      secret-key: 'ajksh34h534h34v5gjh'
    user:
      name: admin
      password: secret
      roles: ACTUATOR
  servlet:
    multipart:
      # disable resolving request to MultiPartRequest to get direct access to HttpServletRequest
      enabled: false
      max-file-size: -1
      max-request-size: -1
#  servlet:
#    multipart:
#      # Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes respectively.
#      file-size-threshold: 1MB
#      location: /tmp
#      max-file-size: 5MB
#      max-request-size: 25MB
#      # resolve-lazily: false
  thymeleaf:
    cache: false
    mode: HTML
    # Order of the template resolver in the chain. (order 1 is the common classpath resolver)
    template-resolver-order: 2

---

server:
  servlet:
    session:
      cookie:
        secure: true

spring:
  config:
    activate:
      on-profile: PROD
  thymeleaf:
    cache: true
