cudami:
  server:
    url: http://localhost:9000
#  webpages:
#    content: 'c4c4b166-06d4-406a-9e6b-b5b7ce0afc9d'
#    footer: '254bc49e-3ce3-43f5-8af0-9bc396da107b'
  website: '855ecb67-b2e8-459d-ace3-c48cf77b9bec'
template:
  name: colorlib-sidebar-v2
  nav-max-level: 3