FROM maven:3.6.3-jdk-11-slim

ARG EUPHORIA_VERSION

ADD https://github.com/dbmdz/streaming-server-euphoria/releases/download/$EUPHORIA_VERSION/streaming-server-euphoria-$EUPHORIA_VERSION-exec.jar euphoria.jar

ENTRYPOINT [ "sh", "-c", "java -jar /euphoria.jar --management.server.port=9001 --server.port=9000 --spring.config.additional-location=file:/application-media.yml" ]
