CREATE TABLE IF NOT EXISTS geo_canyons (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_caves (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_continents (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_countries (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_creeks (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_lakes (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_mountains (height smallint, LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_oceans (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_rivers (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_seas (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_stillwaters (LIKE geolocations INCLUDING all) INHERITS (geolocations);
CREATE TABLE IF NOT EXISTS geo_valleys (LIKE geolocations INCLUDING all) INHERITS (geolocations);
