CREATE TABLE IF NOT EXISTS headwords (
  uuid UUID PRIMARY KEY,
  label VARCHAR(256) NOT NULL,
  locale VARCHAR NOT NULL,
  last_modified TIMESTAMP DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (label, locale)
);
