-- idenfifiers
ALTER TABLE identifiers
ADD COLUMN IF NOT EXISTS created TIMESTAMP NOT NULL DEFAULT '2016-12-22 00:00:00.000Z',
ADD COLUMN IF NOT EXISTS last_modified TIMESTAMP NOT NULL DEFAULT '2016-12-22 00:00:00.000Z';

-- identifiertypes
ALTER TABLE identifiertypes
ADD COLUMN IF NOT EXISTS created TIMESTAMP NOT NULL DEFAULT '2016-12-22 00:00:00.000Z',
ADD COLUMN IF NOT EXISTS last_modified TIMESTAMP NOT NULL DEFAULT '2016-12-22 00:00:00.000Z';

-- predicates
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; -- needed for generation of random UUID

ALTER TABLE predicates
ADD COLUMN IF NOT EXISTS uuid UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4();

-- renderingtemplates
ALTER TABLE renderingtemplates
ADD COLUMN IF NOT EXISTS created TIMESTAMP NOT NULL DEFAULT '2016-12-22 00:00:00.000Z',
ADD COLUMN IF NOT EXISTS last_modified TIMESTAMP NOT NULL DEFAULT '2016-12-22 00:00:00.000Z';

-- users
ALTER TABLE users DROP CONSTRAINT users_pkey;

ALTER TABLE users DROP COLUMN IF EXISTS id;

ALTER TABLE users ADD PRIMARY KEY (uuid);
