global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['localhost:9090']
  - job_name: 'cudami'
    scrape_interval: 15s
    metrics_path: /monitoring/prometheus
    static_configs:
      - targets: ['localhost:9001']