{
 "title": "Cudami (REST)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Performance successful GET requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"GET\", status=\"200\"}[1m])/rate(http_server_requests_seconds_count{method=\"GET\", status=\"200\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Performance not found (404) GET requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"GET\", status=\"404\"}[1m])/rate(http_server_requests_seconds_count{method=\"GET\", status=\"404\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Performance successful POST requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"POST\", status=\"200\"}[1m])/rate(http_server_requests_seconds_count{method=\"POST\", status=\"200\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Performance successful PUT requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{method=\"PUT\", status=\"200\"}[1m])/rate(http_server_requests_seconds_count{method=\"PUT\", status=\"200\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}