import {
  FaAngleUp,
  FaAsterisk,
  FaBold,
  FaCode,
  FaEdit,
  FaFilm,
  FaHeading,
  FaImage,
  FaItalic,
  FaLink,
  FaListOl,
  FaListUl,
  FaMinus,
  FaOutdent,
  FaParagraph,
  FaQuoteLeft,
  FaRedo,
  FaStrikethrough,
  FaSubscript,
  FaSuperscript,
  FaTable,
  FaUnderline,
  FaUndo,
  FaWindowMaximize,
} from 'react-icons/fa'

export default {
  blockquote: <FaQuoteLeft />,
  bold: <FaBold />,
  bullet_list: <FaListUl />,
  code_block: <FaCode />,
  code: <FaCode />,
  edit: <FaEdit />,
  em: <FaItalic />,
  footnote: <FaAsterisk />,
  heading: <FaHeading />,
  hr: <FaMinus />,
  iframe: <FaWindowMaximize />,
  image: <FaImage />,
  italic: <FaItalic />,
  join_up: <FaAngleUp />,
  lift: <FaOutdent />,
  link: <FaLink />,
  ordered_list: <FaListOl />,
  paragraph: <FaParagraph />,
  redo: <FaRedo />,
  strikethrough: <FaStrikethrough />,
  strong: <FaBold />,
  subscript: <FaSubscript />,
  superscript: <FaSuperscript />,
  table: <FaTable />,
  underline: <FaUnderline />,
  undo: <FaUndo />,
  video: <FaFilm />,
}
