name: CI

on:
  pull_request:
    branches: [ main, release/* ]
  push:
    branches: [ main, release/* ]
    tags: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          check-latest: true
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Set up cache
        uses: actions/cache@v6
        env:
          cache-name: cache-maven-artifacts
        with:
          key: cudami-cache-java-${{ matrix.java }}-${{ github.run_id }}
          path: |
            ~/.m2/repository
            target
      - name: Check Java codestyle
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          check-latest: true
          node-version: 24
      - name: Check Javascript codestyle
        run: npm ci --legacy-peer-deps && npm run format-check
        working-directory: client
      - name: Build with Maven
        run: mvn -B -U clean verify -Pproduction
    strategy:
      matrix:
        java: [25]
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up cache
        uses: actions/cache@v6
        env:
          cache-name: cache-maven-artifacts
        with:
          key: cudami-cache-java-25-${{ github.run_id }}
          path: |
            ~/.m2/repository
            target
      - name: Publish code coverage reports
        uses: codecov/codecov-action@v7
  release:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up cache
        uses: actions/cache@v6
        env:
          cache-name: cache-maven-artifacts
        with:
          key: cudami-cache-java-25-${{ github.run_id }}
          path: |
            ~/.m2/repository
            target
      - name: Install XML utils
        run: sudo apt update && sudo apt install libxml2-utils
      - name: Extract project version
        run: echo "PROJECT_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)" >> $GITHUB_ENV
      - name: Create GitHub release
        if: "!endswith(env.PROJECT_VERSION, 'SNAPSHOT') && env.PROJECT_VERSION == github.ref_name"
        uses: softprops/action-gh-release@v3
        with:
          files: |
            target/cudami-${{ env.PROJECT_VERSION }}.jar
          name: "${{ env.PROJECT_VERSION }}"
          prerelease: ${{ contains(env.PROJECT_VERSION, '-rc.') }}
          tag_name: "${{ github.ref_name }}"
